### ISSUE TITLE
I am getting a 404 Time not found error

### ISSUE THREAD

**Issue by rithikjain** [mdhishaamakhtar/learning-schedule#1]

**Comment by ramaneswaran** [comment]
I found a fix for this, use a priority based scheduling for your tasks, this wont give you more time,but you can optimize the usage of your resources

**Comment by rithikjain** [comment]
Ohh makes sense. I tried doing this but I guess my hardware is too slow, so no results.

**Comment by mdhishaamakhtar** [comment]
This repo just contains markdowns. Can you explain your issues a bit more in detail?
